### ISSUE TITLE
Add new field from the Transaction event to TheGraph configuration

### ISSUE THREAD

**Issue by cgdusek** [onomyprotocol/ograph#1]
Please add the "slippage" field from the Transaction event to TheGraph configuration
I added slippage to Solonomy here: https://github.com/onomyprotocol/solonomy/commit/dc8018819fd4aa0676cce4d8d24f94ba0626da3a

**Comment by tpikachu** [comment]
https://github.com/onomyprotocol/ograph/pull/2
